### ISSUE TITLE
TypeScript arguments trouble

### ISSUE THREAD

**Issue by antonmarin** [screepers/typed-screeps#22] opened 2017-11-25 21:56 UTC
```
const receivers = creep.room.find(FIND_MY_SPAWNS);
        const receiver = receivers[0];
        if (creep.transfer(receiver, RESOURCES_ALL) === ERR_NOT_IN_RANGE) {
          creep.moveTo(receiver);
        }
```

Result - error:

> (18,27): Argument of type 'RoomPosition | _HasRoomPosition' is not assignable to parameter of type 'Source | Mineral<MineralConstant>'.
>   Type 'RoomPosition' is not assignable to type 'Source | Mineral<MineralConstant>'.
>     Type 'RoomPosition' is not assignable to type 'Mineral<MineralConstant>'.
>       Property 'density' is missing in type 'RoomPosition'.

Seems like it is related with room.ts:81
`find<T extends _HasRoomPosition | RoomPosition>(type: FindConstant, opts?: { filter: Object | Function | string }): T[];`

**Comment by Arcath** [comment] 2017-11-25 22:35
Could you try using the `2.0.01 branch? We have redone the typings for all the find methods. That code works fine for me minus the `RESOURCES_ALL`.

**Comment by antonmarin** [comment] 2017-11-27 04:18
How to do it? I don't see such release

> 1.0.4 is the latest of 5 releases

**Comment by antonmarin** [comment] 2017-11-27 04:35
Tried
`npm install https://github.com/screepers/typed-screeps.git\#89c8e783dfe0c7c613caf9489dbd51fe8b13746a
`

Got

> ERROR in /Users/antonmarin/WebstormProjects/screeps/node_modules/@types/screeps-profiler/index.d.ts
(123,15): Cannot redeclare block-scoped variable 'Game'.

removed @types/screeps-profiler to test and got new error

> ERROR in /Users/antonmarin/WebstormProjects/screeps/src/Controllers/MaintainersController.ts
(26,70): Property 'energy' does not exist on type 'Structure<StructureConstant>'.

**Comment by resir014** [comment] 2017-11-27 04:38
@antonmarin Try this:

```bash
npm install git://github.com/screepers/typed-screeps.git#2.0.0
```

Once you're done installing, add the following to `tsconfig.json`:

```json
{
  "compilerOptions": {
    "types": ["lodash", "typed-screeps"]
  }
}
```

**Comment by antonmarin** [comment] 2017-11-27 17:46
Tried `npm install git://github.com/screepers/typed-screeps.git#2.0.0`

`npm run deploy`

Result

> ERROR in /Users/antonmarin/WebstormProjects/screeps/node_modules/@types/screeps-profiler/index.d.ts
> (123,15): Cannot redeclare block-scoped variable 'Game'.
 
removed to test and got new error

> ERROR in /Users/antonmarin/WebstormProjects/screeps/src/Controllers/MaintainersController.ts (26,70): Property 'energy' does not exist on type 'Structure'.

Same error ((

**Comment by resir014** [comment] 2017-11-28 17:33
@antonmarin Could you retry from the `master` branch? We've just merged #16.

```
npm uninstall typed-screeps
npm install git://github.com/screepers/typed-screeps.git
```

**Comment by antonmarin** [comment] 2017-11-28 17:44
Same ((

**Comment by apemanzilla** [comment] 2017-11-28 17:56
I can't reproduce this. There's an unrelated error though, you can't pass `RESOURCES_ALL` to `Creep.transfer`.

**Comment by antonmarin** [comment] 2017-11-28 18:01
```
if (creep.transfer(receiver, RESOURCE_ENERGY) === ERR_NOT_IN_RANGE) {
          creep.moveTo(receiver);
        }
```

more code
```
      } else {
        const receivers = creep.room.find(FIND_STRUCTURES, {
          filter: (receiver) => {
            return (receiver.structureType == STRUCTURE_EXTENSION ||
              receiver.structureType == STRUCTURE_SPAWN ||
              receiver.structureType == STRUCTURE_TOWER) && receiver.energy < receiver.energyCapacity;
          }
        });
        const receiver = receivers[0];
        if (creep.transfer(receiver, RESOURCE_ENERGY) === ERR_NOT_IN_RANGE) {
          creep.moveTo(receiver);
        }
      }
```

**Comment by apemanzilla** [comment] 2017-11-28 18:36
Assuming you're talking about the error on `receiver.energy`, this isn't something that can be easily fixed given the way TypeScript works. I'll look into it, but no promises.

**Comment by apemanzilla** [comment] 2017-11-28 20:32
@antonmarin could you test using #23? It should fix your issue.

**Comment by antonmarin** [comment] 2017-11-29 03:43
`npm install git://github.com/screepers/typed-screeps.git#improve-structure-types`?

**Comment by antonmarin** [comment] 2017-11-29 03:48
Seems like it's worked, but there is a conflict with screeps-profiler

**Closed** 2017-11-29 07:17 UTC

**Comment by antonmarin** [comment] 2017-11-29 17:07
Thanks
